services:
  - type: web
    name: tms-backend-atpl-reihana
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
      - key: JWT_SECRET
      - key: BREVO_API_KEY
      - key: SENDER_EMAIL