services:
  - type: web
    name: tms-backend-atpl-2vr9
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node init_db.js && node server.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: SENDER_EMAIL
        sync: false